name: github-actions-basics
env:
  APPLICATION_NAMR: "MyFlask"
  DEPLOY_PACKAGE_NAME    : "flask-deploy-ver-${{ github.sha }}"

on: 
  push:
    branches:
      - master
      
jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name : print hello message in testing
      run : echo "hello world from testing job"

    - name: execute some commands
      run : |
        echo "hello message1"
        exho "hello message2"
        echo "application name: ${{ env.APPLICATION_NAME }}"
  |
      
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
    - name : print hello message in deploy
      run : echo " hello world from deploy job"

    - name: printing deployment package
      run : echo "deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
     
