#-------------------------------------------
name: github-actions-basics
env:
  APPLICATION_NAME       : "MyFlask"
  DEPLOY_PACKAGE_NAME    : "flask-deploy-ver-${{ github.sha }}"

on: 
  push:
    branches:
      - master
      
jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: print hello message in testing
      run : echo "hello world from testing job"

    - name: execute some commands
      run : |
        echo "hello message1"
        echo "hello message2"
        echo "application name: ${{ env.APPLICATION_NAME }}"

    - name: list current folder
      run : ls -la

    - name: git clone my repo
      uses: actions/checkout@v1

    - name: list current folder
      run : ls -la
      
        
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      VAR1 : "this is job level variable1"
      VAR2 : "this is job level variable2"
    
    
    steps:
    - name: print hello message in deploy
      run : echo " hello world from deploy job"

    - name: " print env vars"
      run: |
        echo " Var1 = ${{ env.VAR1 }}"
        echo " Var2 = ${{ env.VAR2 }}"
        echo " Var3 = $LOCAL_VAR"
      env:
        LOCAL_VAR: "this is super local environment variable"
        

    - name: printing deployment package
      run : echo "deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"

    - name: let's terst some packages if exist1
      run : aws --version

    - name: let's terst some packages if exist2
      run : zip
